In [4]:
print("sriram")

sriram


# Revising Python

In [7]:
x=2+3j
print(x)

(2+3j)


In [9]:
%whos

Variable   Type       Data/Info
-------------------------------
x          complex    (2+3j)


In [11]:
print(type(x))

<class 'complex'>


In [12]:
del x

In [15]:
del a,c,d

In [26]:
isinstance(2+3j,(float,int,complex))


True

In [38]:
round(-17.9)

-18

In [28]:
z=input("No please")

No please5


In [29]:
print(z)

5


In [31]:
input??

In [37]:
a=int(input('Enter A Value : '))
b=int(input('Enter B Value : '))
if a>b:
    print("A is bigger : ", str(a))
elif a==b:
    print("No are same")    
else:
    print("B is Bigger")


Enter A Value : 101
Enter B Value : 10
A is bigger :  101


In [43]:
L=[]
for i in range(5):
    print(i)
    L.append(i*2)
print(L)

0
1
2
3
4
[0, 2, 4, 6, 8]


In [48]:
s={"Sri",10,"end",100}
i=0
for x in s:
    print(x)
    i+=1
    if i == 2:
        break
else:
    print("Error")
print("Loop completed")
    

Sri
10
Loop completed


In [49]:
d={'A':[1,2,5,7,9],"sri":['ram','sahan','kutty']}
for x in d:
    print(x,d[x])

A [1, 2, 5, 7, 9]
sri ['ram', 'sahan', 'kutty']


In [61]:
def test(*a):
    s=0
    for i in range(len(a)):
        s+=a[i]
    return s

In [62]:
print(test(2,5,8,7,9))

31


In [63]:
L=[1,2,3]
L2=L
L2[0]=-10
print(L)

[-10, 2, 3]


In [210]:
a="Southern cross health society"
print(a[5])
print(a[2:7])
print(a[-1])
print(a[:])
print(a[1:-1])
print(a[-7:])
print(a[0::3])
print(a[::-1])
print(a[::2])

e
uther
y
Southern cross health society
outhern cross health societ
society
Strcshl ct
yteicos htlaeh ssorc nrehtuoS
Suhr rs elhscey


In [109]:
a="  hi, how ,are , you?..I am , doing , good  "
l=a.split(",")
print(l[2])
l=a.lower()
print(l)
l=a.upper()
print(l)
l=a.strip()
print(l)
l=a.replace(',',':')
print(l)

are 
  hi, how ,are , you?..i am , doing , good  
  HI, HOW ,ARE , YOU?..I AM , DOING , GOOD  
hi, how ,are , you?..I am , doing , good
  hi: how :are : you?..I am : doing : good  


In [110]:
L=[x**2 for x in range(10)]
print(L)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [112]:
B={x**2 for x in range(1,10,2)}
print(B)

{1, 9, 81, 49, 25}


In [114]:
print(str(12),"is already existed")

12 is already existed


In [116]:
def testm():
    D={}
    while True:
        StudentID=input("Enter Student ID : ")
        Marklist=input("Enter marks seperated by comma : ")
        morestudent= input("Enter Yes/no for more students")
        if StudentID in D:
            print(StudentID,"Id alredy exist")
        else:
            D[StudentID]=Marklist.split(",")
        if morestudent.lower() == 'no':
            return D

In [117]:
  studentData = testm()

Enter Student ID : 10
Enter marks seperated by comma : 45,60,78,90,50
Enter Yes/no for more studentsy
Enter Student ID : 10
Enter marks seperated by comma : 40,50,60,70
Enter Yes/no for more studentsy
10 Id alredy exist
Enter Student ID : 13
Enter marks seperated by comma : 45,80,81,83,70
Enter Yes/no for more studentsy
Enter Student ID : 15
Enter marks seperated by comma : 55,66,77,88,90
Enter Yes/no for more studentsno


In [118]:
studentData

{'10': ['45', '60', '78', '90', '50'],
 '13': ['45', '80', '81', '83', '70'],
 '15': ['55', '66', '77', '88', '90']}

In [125]:
def avgmarks(D):
    avmMark={}
    for x in D:
        L=D[x]
        s=0
        for marks in L:
            s+=int(marks)
        avmMark[x]=s/len(L)
    return avmMark
            


In [126]:
angm=avgmarks(studentData)

In [128]:
type(angm)

dict

In [127]:
for x in angm:
    print("Student : ",x,"Average marks : ",angm[x])

Student :  10 Average marks :  64.6
Student :  13 Average marks :  71.8
Student :  15 Average marks :  75.2


In [129]:
import numpy as np

In [131]:
a=np.array([1,23,4,56])
print(a)

[ 1 23  4 56]


In [164]:
d=np.array([[[[1,2,3],[2,4,5]],[[6,7,9],[-6,-7,-22]]],[[[-1,-2,-3],[-2,-4,-5]],[[-6,-7,-999],[6,7,9]]]])
print(d)
d.ndim

[[[[   1    2    3]
   [   2    4    5]]

  [[   6    7    9]
   [  -6   -7  -22]]]


 [[[  -1   -2   -3]
   [  -2   -4   -5]]

  [[  -6   -7 -999]
   [   6    7    9]]]]


4

In [171]:
d[2:4,1]

array([], shape=(0, 2, 3), dtype=int32)

In [153]:
d.size

24

In [155]:
d.nbytes

96

In [211]:
a=np.random.permutation(90)
b=np.arange(90)
print(a,'\n',b)

[ 7  9 71 17 45 14 19 41 79 10 11 35  6 49 83 18 28 85 70 52 22 68  5 73
 48 21  3 76 15 86 34 20 54 64 58 42 13 29 37 26 50 46 80 27 39 60 30 65
 74 53 61  2 84 25 78 62 40 72  0 23 67 47 57  1 36 24  8 63 55 69 16 87
 77 75 82 89  4 66 51 81 32 88 31 33 56 59 43 38 12 44] 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]


In [200]:
c=np.random.randn(2,5)

In [201]:
print(c)

[[ 0.88605863  1.65958269 -0.81642183 -0.76563526  1.43801052]
 [-2.28780131  2.22673449  0.89434579  1.14209909 -0.15674455]]


In [206]:
c=np.arange(100).reshape(5,4,5)
print(c)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]

 [[60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]
  [75 76 77 78 79]]

 [[80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


In [214]:
idx = np.argwhere(a == 44)[0]
idx

array([89], dtype=int64)

In [217]:
a=np.array((1,2,3))
a

array([1, 2, 3])

In [218]:
type(a)

numpy.ndarray

In [221]:
import pandas as pd

In [222]:
grade_dict={'A':4,'B':3.5,'C':3,'D':2.5}
grade=pd.Series(grade_dict)

In [223]:
mark_dict={'A':90,'B':80,'C':75,'D':65}
mark=pd.Series(mark_dict)

In [232]:
mark
grade


A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64

In [235]:
D=pd.DataFrame({'Grade':grade,'Marks':mark})
D

Grade  Marks
A    4.0     90
B    3.5     80
C    3.0     75
D    2.5     65

In [240]:
mark[0:2]

A    90
B    80
dtype: int64

In [241]:
D.T

A     B     C     D
Grade   4.0   3.5   3.0   2.5
Marks  90.0  80.0  75.0  65.0

In [246]:
D['Scaled Marks']=round(100*(D['Marks']/90))
D

Grade  Marks  Scaled Marks
A    4.0     90         100.0
B    3.5     80          89.0
C    3.0     75          83.0
D    2.5     65          72.0

In [249]:
D.values

array([[  4. ,  90. , 100. ],
       [  3.5,  80. ,  89. ],
       [  3. ,  75. ,  83. ],
       [  2.5,  65. ,  72. ]])

In [253]:
D.values[1:3,1:3]

array([[80., 89.],
       [75., 83.]])

In [260]:
G=D[D["Marks"]>70]
G

Grade  Marks
A    4.0     90
B    3.5     80
C    3.0     75